name: mythesis_env_combined_test_clone_six
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - defaults/osx-arm64::blas==1.0=openblas
  - defaults/osx-arm64::bzip2==1.0.8=h80987f9_6
  - conda-forge/osx-arm64::c-ares==1.34.4=h5505292_0
  - defaults/osx-arm64::ca-certificates==2024.12.31=hca03da5_0
  - conda-forge/osx-arm64::jpeg==9e=h1a8c8d9_3
  - conda-forge/osx-arm64::libcxx==19.1.6=ha82da77_1
  - conda-forge/osx-arm64::libdeflate==1.14=h1a8c8d9_0
  - defaults/osx-arm64::libev==4.33=h1a28f6b_1
  - defaults/osx-arm64::libffi==3.4.4=hca03da5_1
  - conda-forge/osx-arm64::liblzma==5.6.3=h39f12f2_1
  - conda-forge/osx-arm64::libwebp-base==1.5.0=h2471fea_0
  - conda-forge/osx-arm64::libzlib==1.3.1=h8359307_2
  - defaults/osx-arm64::llvm-openmp==14.0.6=hc6e5704_0
  - conda-forge/osx-arm64::ncurses==6.5=h7bae524_1
  - defaults/osx-arm64::pthread-stubs==0.3=h1a28f6b_1
  - defaults/noarch::tzdata==2024b=h04d1e81_0
  - conda-forge/osx-arm64::xorg-libxau==1.0.12=h5505292_0
  - conda-forge/osx-arm64::xorg-libxdmcp==1.1.5=hd74edd7_0
  - defaults/osx-arm64::xz==5.4.6=h80987f9_1
  - conda-forge/osx-arm64::yaml==0.2.5=h3422bc3_2
  - conda-forge/osx-arm64::gmp==6.2.1=h9f76cd9_0
  - conda-forge/osx-arm64::lerc==4.0.0=h9a09cb3_0
  - conda-forge/osx-arm64::libabseil==20240722.0=cxx17_h07bc746_4
  - defaults/osx-arm64::libaec==1.1.3=h313beb8_0
  - defaults/osx-arm64::libedit==3.1.20230828=h80987f9_0
  - conda-forge/osx-arm64::libgfortran5==13.2.0=hf226fd6_3
  - conda-forge/osx-arm64::libpng==1.6.45=h3783ad8_0
  - conda-forge/osx-arm64::libsqlite==3.47.2=h3f77e49_0
  - conda-forge/osx-arm64::libxcb==1.13=h9b22ae9_1004
  - defaults/osx-arm64::lz4-c==1.9.4=h313beb8_1
  - defaults/osx-arm64::ninja-base==1.12.1=h48ca7d4_0
  - conda-forge/osx-arm64::openssl==3.4.0=h81ee809_1
  - defaults/osx-arm64::readline==8.2=h1a28f6b_0
  - conda-forge/osx-arm64::sleef==3.5.1=h156473d_2
  - conda-forge/osx-arm64::tk==8.6.13=h5083fa2_1
  - conda-forge/osx-arm64::zlib==1.3.1=h8359307_2
  - conda-forge/osx-arm64::zstd==1.5.6=hb46c0d2_0
  - conda-forge/osx-arm64::freetype==2.12.1=hadb7bae_2
  - defaults/osx-arm64::krb5==1.21.3=hf3e1bf2_0
  - conda-forge/osx-arm64::libgfortran==5.0.0=13_2_0_hd922786_3
  - conda-forge/osx-arm64::libnghttp2==1.64.0=h6d7220d_0
  - conda-forge/osx-arm64::libprotobuf==5.28.3=h3bd63a1_1
  - conda-forge/osx-arm64::libre2-11==2024.07.02=h07bc746_2
  - conda-forge/osx-arm64::libssh2==1.11.1=h9cc3647_0
  - conda-forge/osx-arm64::libtiff==4.4.0=heb92581_5
  - conda-forge/osx-arm64::mpfr==4.2.1=h9546428_0
  - conda-forge/osx-arm64::python==3.10.16=h870587a_1_cpython
  - conda-forge/osx-arm64::sqlite==3.47.2=hd7222ec_0
  - defaults/osx-arm64::brotli-python==1.0.9=py310h313beb8_9
  - defaults/osx-arm64::certifi==2024.12.14=py310hca03da5_0
  - conda-forge/noarch::charset-normalizer==3.4.1=pyhd8ed1ab_0
  - conda-forge/noarch::colorama==0.4.6=pyhd8ed1ab_1
  - conda-forge/noarch::einops==0.8.0=pyhd8ed1ab_1
  - conda-forge/noarch::filelock==3.16.1=pyhd8ed1ab_1
  - conda-forge/noarch::fsspec==2024.12.0=pyhd8ed1ab_0
  - defaults/osx-arm64::future==1.0.0=py310hca03da5_0
  - conda-forge/noarch::hpack==4.0.0=pyhd8ed1ab_1
  - conda-forge/noarch::hyperframe==6.0.1=pyhd8ed1ab_1
  - conda-forge/noarch::idna==3.10=pyhd8ed1ab_1
  - defaults/osx-arm64::lcms2==2.12=hba8e193_0
  - conda-forge/osx-arm64::libcurl==8.11.1=h73640d1_0
  - defaults/osx-arm64::libopenblas==0.3.21=h269037a_0
  - conda-forge/noarch::markupsafe==3.0.2=pyhe1237c8_1
  - conda-forge/osx-arm64::mpc==1.3.1=h91ba8db_0
  - conda-forge/noarch::mpmath==1.3.0=pyhd8ed1ab_1
  - conda-forge/noarch::networkx==3.4=pyhd8ed1ab_0
  - defaults/osx-arm64::ninja==1.12.1=hca03da5_0
  - defaults/osx-arm64::openjpeg==2.4.0=h0ed58ac_2
  - conda-forge/noarch::packaging==24.2=pyhd8ed1ab_2
  - conda-forge/noarch::pycparser==2.22=pyh29332c3_1
  - conda-forge/noarch::pysocks==1.7.1=pyha55dd90_7
  - defaults/noarch::python-tzdata==2023.3=pyhd3eb1b0_0
  - conda-forge/osx-arm64::python_abi==3.10=2_cp310
  - defaults/osx-arm64::pyyaml==6.0.2=py310h80987f9_0
  - conda-forge/osx-arm64::re2==2024.07.02=h6589ca4_2
  - defaults/osx-arm64::safetensors==0.4.5=py310hf4b39b5_1
  - conda-forge/noarch::setuptools==75.6.0=pyhff2d567_1
  - defaults/noarch::six==1.16.0=pyhd3eb1b0_1
  - conda-forge/noarch::typing_extensions==4.12.2=pyha770c72_1
  - defaults/osx-arm64::wheel==0.44.0=py310hca03da5_0
  - defaults/osx-arm64::cffi==1.17.1=py310h3eb5a62_1
  - conda-forge/noarch::cpython==3.10.16=py310hd8ed1ab_1
  - defaults/osx-arm64::gmpy2==2.1.2=py310h8c48613_0
  - conda-forge/noarch::h2==4.1.0=pyhd8ed1ab_1
  - conda-forge/osx-arm64::hdf5==1.14.4=nompi_ha698983_105
  - conda-forge/noarch::jinja2==3.1.5=pyhd8ed1ab_0
  - conda-forge/osx-arm64::libgrpc==1.67.1=h0a426d6_1
  - defaults/osx-arm64::numpy==1.22.3=py310hdb36b11_0
  - defaults/osx-arm64::pip==24.2=py310hca03da5_0
  - conda-forge/osx-arm64::protobuf==5.28.3=py310h853098b_0
  - defaults/osx-arm64::python-dateutil==2.9.0post0=py310hca03da5_2
  - conda-forge/noarch::tqdm==4.67.1=pyhd8ed1ab_1
  - conda-forge/noarch::typing-extensions==4.12.2=hd8ed1ab_1
  - defaults/osx-arm64::bottleneck==1.4.2=py310hbda83bc_0
  - conda-forge/osx-arm64::grpcio==1.67.1=py310h92b281b_1
  - defaults/osx-arm64::numexpr==2.8.7=py310hecc3335_0
  - conda-forge/osx-arm64::onnx==1.17.0=py310h357cfac_2
  - defaults/osx-arm64::scipy==1.12.0=py310h20cbe94_0
  - conda-forge/noarch::sympy==1.13.3=pyh2585a3b_105
  - defaults/osx-arm64::zstandard==0.23.0=py310h1a4646a_1
  - defaults/osx-arm64::pandas==2.2.2=py310h313beb8_0
  - apple/osx-arm64::tensorflow-deps==2.9.0=0
  - conda-forge/noarch::urllib3==2.3.0=pyhd8ed1ab_0
  - conda-forge/noarch::requests==2.32.3=pyhd8ed1ab_1
  - conda-forge/noarch::huggingface_hub==0.27.1=pyhd8ed1ab_0
  - conda-forge/noarch::timm==1.0.12=pyhd8ed1ab_1
prefix: /opt/miniconda3/envs/mythesis_env_combined_test_clone_six
